# Generated by Django 2.0 on 2018-02-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_remove_message_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='urgent',
            field=models.SmallIntegerField(),
        ),
    ]
